language: cpp
compiler:
  - gcc
script: make -j4 && make test -j4

# need to install the Boost libraries to the sandbox
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev libboost-test-dev

notifications:
  email:
    recipients: jeramie.vens@gmail.com
    on_success: change
    on_failure: always
